### PR TITLE
Support parsing of <center> element for ways (XML only)

### PR DESCRIPTION
**Pull request by gregrs-uk**
The 'out center' Overpass QL option provides a centroid for each way in a <center> element. I've added support for parsing the <center> element, but N.B. only for ways (not relations) and only for XML (not JSON).

I've also corrected a mistake in the 'Unknown element end' KeyError message.

### CODE REVIEW

**Comment by phibos** [comment]
Thanks for your contribution. Some tests failed with the following error message.

```
UnboundLocalError: local variable 'center_lat' referenced before assignment
```

Can you please provide a query to test your changes and/or write a test.

**Comment by gregrs-uk** [comment]
I've fixed [`__init__.py`](https://github.com/gregrs-uk/python-overpy/blob/way-center/overpy/__init__.py) in a few places.

I've also added a test involving [another XML file](https://github.com/gregrs-uk/python-overpy/blob/way-center/tests/xml/way-03.xml). This represents the same way used in another test, but is what would be returned if the `out center` Overpass QL option is used.

N.B. the query I used also included the `(._;>;);` option, which means that the XML includes `<node>` elements. This is probably good because it means we can test the `overpy.Way.nodes` property. However, it's not compulsory to return `<node>` elements in the XML if the `out center` option is used on its own.

**Comment by phibos** [comment]
Thanks for your contribution. I had a quick look at your code. But I will do some more tests before merging it.

**Comment by Gloix** [comment]
Hi, @phibos could you test this PR?

**Comment by phibos** [comment]
I have merged the source with the latest master branch and have created a new pull request #47

**Pull request merged**
