### PR TITLE
Add GitHub Actions and set support to Python 2.7,3.6-3.9

### PR DESCRIPTION
**Pull request by eumiro**
##### Issue type
 - Maintenance

##### Summary

Add GitHub Actions CI and set the currently tested versions to 2.7, 3.6, 3.7, 3.8, and 3.9.

I've kept the 2.7, but would like to ask you to consider dropping it. Python 3.6 is the oldest currently supported version, so I have dropped all prior Python 3.x versions.

The results of the GitHub Actions CI won't be immediately visible as it is still not in the `master` branch, but will appear after the merge.

### CODE REVIEW

**Comment by eumiro** [comment]
You can see the results of the GitHub Actions CI at https://github.com/eumiro/python-overpy/actions/runs/506314306

**Comment by phibos** [comment]
Thanks for your contribution. Do we still need to test against Python 2.7? It has been deprecated this year.

**Comment by phibos** [comment]
The github actions also report the coverall statistics? Does it make any sense to keep the travis builds?

**Comment by eumiro** [comment]
Of course, 2.7 should be dropped, but let's do it step by step:
1. see that GHA works
2. drop Travis
3. drop Python 2.7 and refactor the code to Python 3

We're at 1. :-)

**Comment by eumiro** [comment]
And GHA works: https://github.com/eumiro/python-overpy/actions/runs/506314306

**Comment by phibos** [comment]
I have split your changes into multiple PRs (#89, #91 and #93). Thanks for your work. Please contact me if anything is missing.

**Pull request closed without merging**
