### PR TITLE
add helper methods

### PR DESCRIPTION
**Pull request by MorrisJobke**
* `get_street` and `get_intersection`

### CODE REVIEW

**Comment by phibos** [comment]
Looks good, but we should make the 'api' argument optional and create a new instance if not given.

    def get_street(street, areacode, api=None):
        if api is None:
            api = overpy.Overpass()
        ...

**Comment by MorrisJobke** [comment]
> Looks good, but we should make the 'api' argument optional and create a new instance if not given.

Will do that.

**Comment by MorrisJobke** [comment]
Done :)

**Comment by phibos** [comment]
I have merged your changes. Thanks for your contribution.

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
